
name: Docker CI Notification 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: push docker image 
        uses: docker/push-action@v1
        with: 
          username: $ {{ secrets.DOCKER_USERNAME }}
          password: $ {{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          respository: ericiachan/devops-cicd-dockerrepo
          tag_with_ref: true 
    
      
