
name: CI


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Build and push Docker images
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.6.1
        with:
          push: true
          tags: ericiachan/devops-cicd-dockerrepo:latest
          
          
  send: 
    name: send telegram message
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: send default message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: The ${{ github.event_name }} event triggered first step.

#   notify:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@main
#       - uses: themakers/telegram-action@master
#         with: 
#           token: ${{ secrets.TELEGRAM_TOKEN }}
#           to: ${{ secrets.TELEGRAM_TO }}

#   notify:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Notifier
#     - uses: GokulDas027/TelegramBridge@master
#       if: always()
#       with:
#         chat: ${{ secrets.chat }} # save your chat id at settings/secrets with name: chat
#         token: ${{ secrets.token }} # savethe bot token at settings/secrets with name: token
#         status: ${{ job.status }} # don't change
#         event: ${{ github.event_name }} # don't change
#         actor: ${{ github.actor }} # don't change



          


