
name: CI


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Docker images
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.6.1
        with:
          push: true
          tags: ericiachan/devops-cicd-dockerrepo:latest
          
#   notify:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@main
#       - uses: themakers/telegram-action@master
#         with: 
#           token: ${{ secrets.TELEGRAM_TOKEN }}
#           to: ${{ secrets.TELEGRAM_TO }}

  send:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: send default message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}

          


